### PR TITLE
Add py39 to set of tested versions

### PR DESCRIPTION
**Pull request by gregjones**
This requires updating tox, which requires a higher version of
six than was being specified.

### CODE REVIEW

**Comment by mortenlj** [comment]
The failing build seems to be caused by real problems, one for py2.7 and a different one for py3.9.

**Comment by oyvindio** [comment]
> The failing build seems to be caused by real problems, one for py2.7 and a different one for py3.9.

The py2.7 CI issue looks similar to an issue that happened in fiaas-deploy-daemon CI earlier. If I remember correctly, that was resolved by pinning setuptools and virtualenv versions (https://github.com/fiaas/fiaas-deploy-daemon/pull/141).

**Comment by gregjones** [comment]
I think what's there now is the minimal change to get it working in both 2.7 and 3.9

**Review by adv-spinnaker — APPROVED** [review]

**Review by adriengentil — DISMISSED** [review]
With the right user :facepalm:

**Review by amanya — APPROVED** [review]

**Review by oyvindio — APPROVED** [review]

**Comment by gregjones** [comment]
I'm not sure what's happening with Codacy... here it shows it has evaluated the PR: https://app.codacy.com/manual/fiaas/k8s/pullRequest?prid=7058109 🤔

**Comment by gregjones** [comment]
Ah, I see there are two. I guess they changed their identifier. I will remove the old one and mark the new one as 'required'

**Review by oyvindio — APPROVED** [review]

**Pull request merged**
